name: Test package
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '12', '14' ]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run build

      - run: npm test